### ISSUE TITLE
Typo in render_shepherdaddstep?

### ISSUE THREAD

**Issue by ogobrecht** [Dani3lSun/apex-plugin-guidedtour#1]
Hi Daniel,

may be I found a typo by looking in your source code. I am writing at the moment my first dynamic action plugin and searching for a way to access the affected elements of a true action. Do you know, how I can do this?

Oh, and here the typo - I think you want to have attribute_07 here:

```
  l_result.attribute_06        := l_btn_next_text;
  l_result.attribute_06        := l_position;
  --
  RETURN l_result;
  --
END render_shepherdaddstep;
```

Best Regards,
Ottmar Gobrecht

**Comment by Dani3lSun** [comment]
Hi Ottmar,
thanks for the hint I will correct that after writing this!:)
In my plugin this copy&paste error does not affect anything because I write the JS code inline at page load using apex_javascript.add_inline_code. But if you write a your own javascript file and add that to the plugin files the l_result array is important, thus this assignment of attributes is usable in your JS code. A good example would be my screen capture plugin:
https://github.com/Dani3lSun/apex-plugin-apexscreencapture/blob/master/server/apexscreencapture.js
To address the affected elements this is possible in your javascript code using

```
var vAffectedElements = this.affectedElements;
```

I hope this helps!

Regards
Daniel

**Comment by ogobrecht** [comment]
Hi Daniel,

thanks for the hint. In the meantime I remembered also the `this` keyword and tried it out by logging it to the console with this line of code:

```
v_result.javascript_function := q'# function(){ console.log('this:', this); } #';
```

And there I found everything I need - thanks again for your help :-)

Regards
Ottmar
